# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [17]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [15]:
weather_stuff = pd.read_csv('../Output/weather_data.csv')
weather_stuff

,Unnamed: 0,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Wind Speed,Max Temp
0,0,Butaritari,40,KI,1613158266,82,3.0707,172.7902,9.82,80.80
1,1,Arraial do Cabo,90,BR,1613158095,74,-22.9661,-42.0278,20.71,82.40
2,2,Cape Town,20,ZA,1613158152,83,-33.9258,18.4232,19.57,72.00
3,3,Vardø,75,NO,1613158269,92,70.3705,31.1107,13.80,15.80
4,4,Esperance,19,AU,1613158128,88,-33.8667,121.9000,4.61,57.20
...,...,...,...,...,...,...,...,...,...,...
569,569,Virginia Beach,90,US,1613158977,87,36.8529,-75.9780,12.66,41.00
570,570,General Roca,0,AR,1613158742,22,-39.0333,-67.5833,11.50,93.20
571,571,Tsiroanomandidy,100,MG,1613158980,94,-18.7667,46.0333,5.32,67.42
572,572,Abalak,92,RU,1613158981,89,58.1286,68.5944,5.91,-11.45
573,573,Moratuwa,0,LK,1613158982,88,6.7730,79.8816,6.91,75.20

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [19]:
gmaps.configure(api_key=g_key)

In [20]:
locations = weather_stuff[["Lat", "Lng"]].astype(float)
# Convert Poverty Rate to float and store
weather_final = weather_stuff.dropna()
humid_weight = weather_stuff["Humidity"].astype(float)

In [21]:
fig = gmaps.figure()

heat_layer = gmaps.heatmap_layer(locations, weights=humid_weight, 
                                 dissipating=False, max_intensity=100,
                                 point_radius = 1)

fig.add_layer(heat_layer)

fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [25]:
vacay_city_df = weather_stuff.loc[(weather_stuff["Max Temp"] > 75) & (weather_stuff["Max Temp"] < 80) & (weather_stuff["Cloudiness"] == 0), :]
vacay_city_df = vacay_city_df.dropna(how='any')
vacay_city_df.reset_index(inplace=True)
del vacay_city_df['index']
vacay_city_df.head()

,Unnamed: 0,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Wind Speed,Max Temp
0,59,Araouane,0,ML,1613158343,13,18.9048,-3.5265,9.75,79.79
1,159,Bonthe,0,SL,1613158465,79,7.5264,-12.5050,9.51,79.79
2,170,Arlit,0,NE,1613158478,16,18.7369,7.3853,12.12,75.76
3,222,Bubaque,0,GW,1613158544,76,11.2833,-15.8333,13.62,77.61
4,238,Hambantota,0,LK,1613158343,100,6.1241,81.1185,4.61,75.20

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [26]:
hotels = []

for i in range(len(vacay_city_df)):
    lat = vacay_city_df.loc[i]['Lat']
    lng = vacay_city_df.loc[i]['Lng']

    params = {
        "location": f"{lat},{lng}",
        "radius": 5000,
        "types" : "hotel",
        "key": g_key
    }
    
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    requested = requests.get(base_url, params=params)
    jsn = requested.json()
    try:
        hotels.append(jsn['results'][0]['name'])
    except:
        hotellist.append("")
vacay_city_df["Hotel Name"] = hotels
vacay_city_df = vacay_city_df.dropna(how='any')
vacay_city_df.head()

,Unnamed: 0,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Wind Speed,Max Temp,Hotel Name
0,59,Araouane,0,ML,1613158343,13,18.9048,-3.5265,9.75,79.79,Araouane
1,159,Bonthe,0,SL,1613158465,79,7.5264,-12.5050,9.51,79.79,Bonthe
2,170,Arlit,0,NE,1613158478,16,18.7369,7.3853,12.12,75.76,Arlit
3,222,Bubaque,0,GW,1613158544,76,11.2833,-15.8333,13.62,77.61,Bubaque
4,238,Hambantota,0,LK,1613158343,100,6.1241,81.1185,4.61,75.20,Hambantota

In [30]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in vacay_city_df.iterrows()]
locations = vacay_city_df[["Lat", "Lng"]]

In [31]:
# Add marker layer ontop of heat map
markers = gmaps.marker_layer(locations)
# Display figure
fig.add_layer(markers)
fig

Figure(layout=FigureLayout(height='420px'))